In [2]:
import numpy as np


In [3]:
%%timeit
[x** 2 for x in range(1, 1000000)]

246 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
np.arange(1, 1_000_000) ** 2

508 µs ± 4.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
370 / 3.04

121.71052631578947

#### C is "closer to the metal than python

Assemble is closer to the metal than C

and Processor instruction sets == are the metal

In [6]:
x = [1, 2, 3, 4, 5]
x = np.array(x)
x, type(x)

#(array([1, 2, 3, 4, 5]), numpy.ndarray)
#nd: nth dimensional

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [7]:
x.shape

(5,)

In [9]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 0, 9]
])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [10]:
type(matrix)

numpy.ndarray

In [11]:
matrix[0]

array([1, 2, 3])

In [12]:
matrix[0][0]

1

In [13]:
matrix[0, 0]

1

In [14]:
first_row = matrix[0]
first_row

array([1, 2, 3])

In [15]:
first_element = first_row[0]
first_element

1

In [16]:
x

array([1, 2, 3, 4, 5])

In [17]:
x, x[1:3]

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [20]:
a = np.array(range(1, 100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
a.sum(), a.mean(), a.min(), a.max(), a.std()

(4950, 50.0, 1, 99, 28.577380332470412)

In [22]:
np.median(a)

50.0

In [24]:
b = np.array([2, 3, 4, 5])
should_include_elements = np.array([False, True, False, True])
b[should_include_elements]

array([3, 5])

In [25]:
should_include_rows = np.array([False, True, True])
matrix[should_include_rows]

array([[4, 5, 6],
       [7, 0, 9]])

## Array of Booleans == Beating heard of Filtering/Transforing Arrays

- this is how we can do loop-like stuff w/o loops

- This "spell" is called "Boolean Masking", and folks may "array filtering" or 'indexing'

In [26]:
x = np.array([1, 2, 3, 4, 5])

In [27]:
x == 3

array([False, False,  True, False, False])

In [28]:
x < -9

array([False, False, False, False, False])

In [29]:
x >3

array([False, False, False,  True,  True])

In [30]:
x % 2 == 0

array([False,  True, False,  True, False])

In [31]:
only_threes = x ==3
x[only_threes]

array([3])

In [32]:
x[x == 3]

array([3])

In [33]:
x[x < 0]

array([], dtype=int64)

In [34]:
x[x > 3]

array([4, 5])

In [36]:
evens_from_x = x[x % 2 ==0]
evens_from_x

array([2, 4])

In [37]:
def remove_evens(x):
    return x[x % 2 == 0]

remove_evens([2, 3, 34, 5, 6, 24, 442, 24, 12, 3, 24, 3, 3, 23, 23, 23, 10])

#must input an array, rather than the inputted LIST

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [38]:
def remove_evens(x):
    x = np.array(x)
    return x[x % 2 == 0]

remove_evens([2, 3, 34, 5, 6, 24, 442, 24, 12, 3, 24, 3, 3, 23, 23, 23, 10])

array([  2,  34,   6,  24, 442,  24,  12,  24,  10])

In [39]:
def remove_evens(x):
    x = np.array(x)
    return x[x % 2 == 0]

remove_evens([2, 3, 4, 5, 6])

array([2, 4, 6])

## Intro to Vectorization

- Loop like behaviour on an array w/o the loop

In [40]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
x +1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
type(x[0])

numpy.float64

In [46]:
#(start=inclusive, end=exclusive)
#so the following like is like rolling a 20 sided die
x = np.random.randint(1, 21)
x

10

In [47]:
#3rd argument is the size or number of random numbers
x = np.random.randint(1, 21, 10)
x

array([ 9,  8, 15,  2, 15, 19, 14, 10,  5,  6])

In [49]:
s = np.random.randn(10)
s

array([ 0.63247983, -1.53765542, -0.09829388,  1.02171651,  0.24834638,
        0.21207836, -0.39016284, -0.29056773, -1.69234451, -0.94136636])

In [50]:
type(s[0])

numpy.float64