In [51]:
import numpy as np

In [52]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# 1.
How many negative numbers are there?

In [53]:
neg_a = a[a < 0]

#neg_a
len(neg_a)

4

# 2.
How many positive numbers are there?

In [54]:
def pos_a(a):
    return a[a > 0]

#pos_a(a)
len(pos_a(a))

5

# 3.
How many even positive numbers are there?

In [57]:
#even_a = a[a % 2 ==0]

pos_even_a = pos_a([pos_a % 2 == 0])

len(pos_even_a(a))

TypeError: unsupported operand type(s) for %: 'function' and 'int'

In [61]:
even_pos = a[(a > 0) & (a % 2 == 0)]

even_pos

array([ 4, 10, 12])

# 4. 
If you were to add 3 to each data point, how many positive numbers would there be?

In [58]:
plus_3 = a + 3

#plus_3

pos_a(plus_3)

len(pos_a(plus_3))

10

# 5. 
If you squared each number, what would the new mean and standard deviation be?

In [59]:
a_sqrd = a * a

a_sqrd

a_sqrd.mean(), a_sqrd.std()

(74.0, 144.0243035046516)

# 6.
A common statistical operation on a dataset is **centering**. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering: https://www.theanalysisfactor.com/centering-and-standardizing-predictors/

In [62]:
centered_a = a - a.mean()

centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

# 7. 
Calculate the z-score for each data point. Recall that the z-score is given by:
- z = (x - μ)/ σ


In [63]:
zscore_a = (a - a.mean()) / a.std()

zscore_a

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# 8.
Copy the setup and exercise directions from More Numpy Practice (https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your `numpy_exercises.py` and add your solutions.

In [8]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
#a = np.array(a)
#sum_of_a = a.sum()

sum_of_a = sum(a)

sum_of_a

55

In [10]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
#min_of_a = a.min()
min_of_a = min(a)
min_of_a

1

In [11]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
#max_of_a = a.max()
max_of_a = max(a)
max_of_a

10

In [12]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
#mean_of_a = a.mean()
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [13]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
#product_of_a = a.prod()
def multiplication(num):
    product = 1
    for ele in num:
        product *= ele
    return product

product_of_a = multiplication(a)

product_of_a

3628800

In [14]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
#squares_of_a = np.square(a)
def squared(numbers):
    sqs = []
    for n in numbers:
        sqs.append(n * n)
    return sqs

squares_of_a = squared(a)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [15]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
#odds_in_a = a[a % 2 != 0]
def odd_numbers(digits):
    odd = []
    for d in digits:
        if d % 2 != 0:
            odd.append(d)
        else:
            continue
    return odd

odds_in_a = odd_numbers(a)

odds_in_a

[1, 3, 5, 7, 9]

In [16]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
#evens_in_a = a[a % 2 == 0]
def even_numbers(numeros):
    even = []
    for n in numeros:
        if n % 2 == 0:
            even.append(n)
        else:
            continue
    return even

evens_in_a = even_numbers(a)

evens_in_a

[2, 4, 6, 8, 10]

In [17]:
## What about life in two dimensions? A list of lists is matrix, a table, 
# a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, 
# product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [18]:
# Exercise 1 - refactor the following to use numpy. 
#Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
#sum_of_b = 0
#for row in b:
#    sum_of_b += sum(row)

b = np.array(b)

sum_of_b = b.sum()

sum_of_b

33

In [19]:
# Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

min_of_b = b.min()
min_of_b

3

In [20]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
max_of_b

8

In [21]:
# Exercise 4 - refactor the following using numpy to find the mean of b
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()
mean_of_b

5.5

In [22]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number

product_of_b = b.prod()
product_of_b

20160

# the above functions are methods that live on the array

## others like below live in the numpy library only

In [29]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
#squares_of_b = []
#for row in b:
#    for number in row:
#        squares_of_b.append(number**2)
b = np.array(b)
squares_of_b = np.square(b)
#squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [64]:
np.power(b, 2)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [24]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
#odds_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 != 0):
#            odds_in_b.append(number)

odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

In [25]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#evens_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [26]:
# Exercise 9 - print out the shape of the array b.
np.shape(b)

(2, 3)

In [27]:
# Exercise 10 - transpose the array b.
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [65]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [30]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [66]:
b.reshape(6)

array([3, 4, 5, 6, 7, 8])

In [32]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [35]:
# HINT, you'll first need to make sure that the "c" variable is a 
# numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

c = np.array(c)
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [36]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [37]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [39]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [40]:
# Exercise 5 - Transpose c and print out transposed result.
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [67]:
# Exercise 7 - Write the code necessary to sum up the result 
# of c times c transposed. Answer should be 261
t_c = c.transpose()
prod_tc = c * t_c
prod_tc.sum()

261

In [84]:
t_c = c.transpose()
prod_tc = np.dot(c, t_c)
prod_tc.sum()

693

In [85]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
prod_tc.prod()

7968564961280000

In [68]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [69]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [70]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [71]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [74]:
# Exercise 4 - Find all the negative numbers in d
d = np.array(d)

d[d < 0]

array([-90, -30, -45, -45])

In [75]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [76]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [83]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [81]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [82]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T.shape

(6, 3)

In [80]:
# Exercise 10 - Reshape d into an array of 9 x 2

d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])