In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [20]:
# How many negative numbers are there?
negative_numbers = a[a < 0]
len(negative_numbers)

4

In [21]:
# How many positive numbers are there?
positive_numbers = a[a > 0]
len(positive_numbers)

5

In [23]:
# How many even positive numbers are there?
positive_numbers = a[a > 0]
even_positives = positive_numbers[positive_numbers % 2 == 0]
len(even_positives)

3

In [25]:
# How many even positive numbers are there?
# The OR operation is | character
even_positive_numbers = a[(a > 0) & (a % 2 == 0)]
even_positive_numbers

array([ 4, 10, 12])

In [27]:
# If you were to add 3 to each data point, how many positive numbers would there be?
b = a + 3
len(b[b > 0])

10

In [19]:
# If you squared each number, what would the new mean and standard deviation be?
c = a ** 2
c.mean(), c.std()

(74.0, 144.0243035046516)

In [29]:
(a ** 2).mean(), (a ** 2).std()

(74.0, 144.0243035046516)

In [33]:
# Center the array
centered_values = a - a.mean()
centered_values

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [34]:
centered_values.mean()

0.0

In [37]:
# Calculate the z-score for each data point. Recall that the z-score is given by:
z = (a - a.mean()) / a.std()
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [38]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
sum(a)

55

In [40]:
min(a)

1

In [41]:
max(a)

10

In [42]:
sum(a) / len(a)

5.5

In [43]:
total = 1
for n in a:
    total *= n
total

3628800

In [44]:
10*9*8*7*6*5*4*3*2*1

3628800

In [45]:
[n ** 2 for n in a]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [47]:
[n for n in a if n % 2 != 0]

[1, 3, 5, 7, 9]

In [48]:
[n for n in a if n % 2 == 0]

[2, 4, 6, 8, 10]

In [49]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [51]:
b = np.array(b)

In [52]:
b.sum()

33

In [53]:
b.min()

3

In [54]:
b.max()

8

In [55]:
b.mean()

5.5

In [56]:
np.prod(b)

20160

In [57]:
b.prod()

20160

In [61]:
%%timeit
b ** 2

739 ns ± 49.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [60]:
%%timeit
np.power(b, 2)

993 ns ± 69.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [62]:
b[b % 2 != 0]

array([3, 5, 7])

In [63]:
b[b % 2 == 0]

array([4, 6, 8])

In [64]:
b.shape

(2, 3)

In [65]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [66]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [68]:
b.reshape(6)

array([3, 4, 5, 6, 7, 8])

In [72]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [76]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)

In [77]:
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [78]:
c.std()

2.581988897471611

In [79]:
c.var()

6.666666666666667

In [80]:
c.shape

(3, 3)

In [81]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
np.dot(c, c).sum()

729

In [88]:
(np.dot(c, c.T)).sum()

693

In [89]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [90]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [91]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [92]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [94]:
d = np.array(d)
d[d < 0]

array([-90, -30, -45, -45])

In [95]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [97]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [99]:
d.shape

(3, 6)

In [100]:
d.T.shape

(6, 3)

In [101]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])